### ISSUE TITLE
Задача проверить MAC адрес контроллера (ID). 

### ISSUE THREAD

**Issue by Jumperx** [wolf1996/MSM#1]
на какой url и какие данные отправлять?
в документации не увидел.

**Comment by wolf1996** [comment]
Я не понял вопроса, опишите проблему подробнее, пожалуйста.

**Comment by Jumperx** [comment]
3) Введдите MAC адрес контроллера (ID) (обязательное). (Запрос на сервер - проверка соответствия). Если ответ - 200, то следующий шаг. если нет, то пишем об ошибке верификации.

может это вам о чем то скажет 
задача состоит в том что бы проверить мак адрес  контроллера 
вопрос на какой url мне отправлять мак адрес контроллера что бы его проверить

**Comment by wolf1996** [comment]
Если я правильно понял это сообщение для добавления контроллера по mac адресу.  На данный момент в приложении заложен лишь минимальный функционал для демонстрации общей концепции, описанный в swagger. Добавление контроллера\сенсора\юзера в данный в функционал не входит.

**Comment by Jumperx** [comment]
ок, понял спасибо)
